### ISSUE TITLE
Cannot install plugin via sfdx command

### ISSUE THREAD

**Issue by aveselovskyy** [afawcett/dependencies-cli#31] opened 2020-01-27 20:06 UTC
Just trying to install plugin on my Windows machine by doing the following:
```
sfdx update
sfdx plugins:install dependencies-cli
```
The output looks like this - seems like it has just dropped in the middle of fetching packages phase:
```
D:\tmp\DependencyApi>sfdx plugins:install dependencies-cli
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
warning dependencies-cli > babel-preset-latest@6.24.1: We're super 😸  excited that you're trying to use ES2017+ syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
warning dependencies-cli > crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
warning dependencies-cli > babel-preset-latest > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
warning dependencies-cli > babel-preset-latest > babel-preset-es2017@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
warning dependencies-cli > babel-preset-latest > babel-preset-es2016@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
warning dependencies-cli > babel-preset-latest > babel-preset-es2015 > babel-plugin-check-es2015-constants > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
Installing plugin dependencies-cli... - [2/4] Fetching packages...

D:\tmp\DependencyApi>
```

Retried couple times and got exactly same results.
At the same time I have no problems installing other plugins, i.e. sfdx, npm and node installations seems to be fine.

**Comment by hkache** [comment] 2020-01-31 14:14
@aveselovskyy can you please try and run `sfdx plugins:install dependencies-cli -f -v` for verbose output and forced install? Does that change things?

At the same time I would like to close your issue as duplicate of https://github.com/forcedotcom/dependencies-cli/issues/7

Please make sure to head over to the new repo for your work. This version has been deprecated in favor of https://github.com/forcedotcom/dependencies-cli

**Closed as completed by hkache** 2020-01-31 14:14 UTC
